// P1 Pattern/Impact decision gate. Experimental only: shipping combat remains unchanged.
import fs from 'node:fs';import path from 'node:path';
const F=[1,2,3,4,5,6],PAIRS=[[0,1],[0,2],[0,3],[1,2],[1,3],[2,3]];
function rng(seed){let x=seed>>>0;return()=>{x=(x+0x6D2B79F5)|0;let t=x;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
const d6=r=>1+Math.floor(r()*6),opp=(a,b)=>a+b===7;
function pat(v){const m={};for(const x of v)m[x]=(m[x]||0)+1;const c=Object.values(m).sort((a,b)=>b-a),s=[...v].sort((a,b)=>a-b);return{four:c[0]===4,three:c[0]===3,twoPair:c[0]===2&&c[1]===2,pair:c[0]===2&&c[1]===1,unique:c[0]===1,run:new Set(v).size===4&&s[3]-s[0]===3,odd:v.every(x=>x%2),even:v.every(x=>x%2===0)}}
function pp(a,b){return{dbl:a===b,opp:opp(a,b),seq:Math.abs(a-b)===1}}
const BUILDS={baseline:{power:1},margin:{power:3,raw10:4},doubles:{power:2,dbl:7,repeatCounter:true},opposites:{power:2,opp:8},sequence:{power:2,run:9,unique:5},jackpot:{power:2,four:true},greed:{power:2,spDbl:4,spOpp:5,rewardBridge:true},retrigger:{power:2,retrigger:true},misaligned:{power:2,unique:2,spDbl:2},lateSynergy:{power:4,raw10:6,dbl:10,opp:10,four:true,retrigger:true,repeatCounter:true}};
const POLICIES={safe:{dmg:4,sp:0.3,risk:7,res:1},opportunist:{dmg:3,sp:1,risk:4,res:1.5},greedy:{dmg:2,sp:2.3,risk:2,res:1},specialist:{dmg:2.6,sp:0.8,risk:3,res:1.8}};
function impact(model,margin,b,cast,fight,sp,natural,state){if(margin<=0)return{total:0,base:0,add:0,mult:1,after:0};const cp=pat(cast),np=pat(natural),fp=pp(...fight);if(model==='A')return{total:margin,base:margin,add:0,mult:1,after:0};let power=b.power+(b.rewardBridge?Math.min(2,Math.floor(state.reward/18)):0),base=margin*power,add=0,mult=1,after=0;if(model!=='B'){if(b.raw10&&fight[0]+fight[1]>=10)add+=b.raw10;if(b.dbl&&fp.dbl)add+=b.dbl+(b.repeatCounter?Math.min(8,state.repeat):0);if(b.opp&&fp.opp)add+=b.opp;if(b.run&&cp.run)add+=b.run;if(b.unique&&cp.unique)add+=b.unique;if(b.four&&cp.four)mult*=np.four?4:2;if(model==='D'){if(cp.three)add+=6;if(cp.four)add+=12;if(cp.run)add+=5;}if(b.retrigger&&fp.dbl)after=Math.floor((base+add)*0.5);}const primary=Math.floor((base+add)*mult);return{total:primary+after,base,add,mult,after};}
function manipOptions(v,tools){const o=[{v:[...v],a:'NONE',cost:0}];if(tools.bump>0)for(let i=0;i<4;i++)for(const q of[-1,1]){const n=v[i]+q;if(n>=1&&n<=6){const x=[...v];x[i]=n;o.push({v:x,a:'BUMP',cost:1})}}if(tools.flip>0)for(let i=0;i<4;i++){const x=[...v];x[i]=7-v[i];o.push({v:x,a:'FLIP',cost:1})}if(tools.copy>0)for(let s=0;s<4;s++)for(let t=0;t<4;t++)if(s!==t){const x=[...v];x[t]=x[s];o.push({v:x,a:'COPY',cost:1})}if(tools.trans>0)for(let i=0;i<4;i++)for(const n of[1,6])if(v[i]!==n){const x=[...v];x[i]=n;o.push({v:x,a:'TRANS',cost:1})}return o;}
function loadout(build){if(build==='opposites')return{bump:1,flip:1,copy:0,trans:0};if(build==='jackpot')return{bump:1,flip:0,copy:1,trans:1};if(build==='sequence')return{bump:1,flip:0,copy:0,trans:0};if(build==='retrigger')return{bump:1,flip:0,copy:1,trans:0};if(build==='lateSynergy')return{bump:2,flip:1,copy:1,trans:1};return{bump:1,flip:0,copy:0,trans:0}}
function choose(cast,enemy,bn,model,pn,state,tools){const b=BUILDS[bn],p=POLICIES[pn];let best=null,combatBest=-1e9,rewardBest=-1e9;for(const mo of manipOptions(cast,tools))for(const [i,j] of PAIRS){const rest=[0,1,2,3].filter(k=>k!==i&&k!==j),fight=[mo.v[i],mo.v[j]],sp=[mo.v[rest[0]],mo.v[rest[1]]],margin=fight[0]+fight[1]-enemy.fight,im=impact(model,margin,b,mo.v,fight,sp,cast,state),spp=pp(...sp),cp=pat(mo.v);let spv=sp[0]+sp[1]+(b.spDbl&&spp.dbl?b.spDbl:0)+(b.spOpp&&spp.opp?b.spOpp:0);const incoming=Math.max(0,-margin),pattern=(b.dbl&&pp(...fight).dbl?b.dbl:0)+(b.opp&&pp(...fight).opp?b.opp:0)+(b.run&&cp.run?b.run:0)+(b.unique&&cp.unique?b.unique:0)+(b.four&&cp.four?18:0);const util=im.total*p.dmg+spv*p.sp+pattern*(pn==='specialist'?2:0.4)-incoming*p.risk-mo.cost*p.res+(im.total>=enemy.hp?8:0);combatBest=Math.max(combatBest,im.total*4-incoming*5);rewardBest=Math.max(rewardBest,spv*3+(margin>0?3:-20));const x={util,margin,im,spv,action:mo.a,fight,sp,cast:mo.v,cp,fp:pp(...fight),spp,incoming};if(!best||util>best.util)best=x;}best.tension=Math.abs(combatBest-rewardBest)>6&&best.margin>0;return best;}
const ENEMIES={normal:{hp:22,fight:[5,6,7]},elite:{hp:58,fight:[7,8,9]},boss:{hp:130,fight:[8,9,10]}};
function fight(seed,bn,model,pn,kind){const r=rng(seed),b=BUILDS[bn],base=ENEMIES[kind],enemy={hp:base.hp,fight:base.fight[Math.floor(r()*base.fight.length)]},state={hp:60,reward:0,repeat:0},tools=loadout(bn),stats={rounds:0,damage:[],sp:[],patterns:{four:0,three:0,run:0,unique:0},naturalFour:0,manufacturedFour:0,manips:0,tension:0,overkill:0,base:0,add:0,after:0,multExtra:0};while(enemy.hp>0&&state.hp>0&&stats.rounds<30){stats.rounds++;enemy.fight=base.fight[Math.floor(r()*base.fight.length)];const cast=[d6(r),d6(r),d6(r),d6(r)],d=choose(cast,enemy,bn,model,pn,state,tools);if(d.action!=='NONE'){stats.manips++;tools[d.action.toLowerCase()]>0&&tools[d.action.toLowerCase()]--;}if(d.tension)stats.tension++;if(d.margin>0){const before=enemy.hp;enemy.hp-=d.im.total;stats.overkill+=Math.max(0,d.im.total-before);stats.damage.push(d.im.total);stats.sp.push(d.spv);state.reward+=d.spv;stats.base+=d.im.base;stats.add+=d.im.add;stats.after+=d.im.after;stats.multExtra+=Math.max(0,d.im.total-d.im.base-d.im.add-d.im.after);if(d.fp.dbl&&b.repeatCounter)state.repeat++;for(const k of['four','three','run','unique'])if(d.cp[k])stats.patterns[k]++;if(d.cp.four){if(pat(cast).four)stats.naturalFour++;else stats.manufacturedFour++;}}else state.hp-=Math.max(1,d.incoming||1);}return{win:enemy.hp<=0,playerHp:state.hp,...stats};}
function q(a,p){if(!a.length)return 0;const s=[...a].sort((x,y)=>x-y);return s[Math.min(s.length-1,Math.floor((s.length-1)*p))]}
function run(n=600){const rows=[];for(const model of['A','B','C','D'])for(const bn of Object.keys(BUILDS))for(const pn of Object.keys(POLICIES))for(const kind of Object.keys(ENEMIES)){const fs=[];for(let i=0;i<n;i++)fs.push(fight(1000003+i*7919+bn.length*101+model.charCodeAt(0)*17+pn.length*31+kind.length*43,bn,model,pn,kind));const dmg=fs.flatMap(x=>x.damage),sum=k=>fs.reduce((a,x)=>a+x[k],0);rows.push({model,build:bn,policy:pn,kind,runs:n,winRate:sum('win')/n,avgRounds:sum('rounds')/n,avgHp:sum('playerHp')/n,damage:{p10:q(dmg,.1),median:q(dmg,.5),p90:q(dmg,.9),p99:q(dmg,.99),max:Math.max(0,...dmg)},avgSpoils:fs.flatMap(x=>x.sp).reduce((a,x)=>a+x,0)/Math.max(1,fs.flatMap(x=>x.sp).length),manipPerFight:sum('manips')/n,tensionRate:sum('tension')/Math.max(1,sum('rounds')),overkill:sum('overkill')/n,naturalFour:sum('naturalFour'),manufacturedFour:sum('manufacturedFour'),component:{base:sum('base'),add:sum('add'),multExtra:sum('multExtra'),after:sum('after')}});}return rows;}
function verdict(rows){const by=m=>rows.filter(x=>x.model===m&&x.policy==='opportunist');const score={};for(const m of['A','B','C','D']){const r=by(m),normal=r.filter(x=>x.kind==='normal'),elite=r.filter(x=>x.kind==='elite'),boss=r.filter(x=>x.kind==='boss'),mis=r.filter(x=>x.build==='misaligned');let s=0;s+=normal.filter(x=>x.avgRounds>=1&&x.avgRounds<=4).length;s+=elite.filter(x=>x.avgRounds>=2.5&&x.avgRounds<=7).length;s+=boss.filter(x=>x.avgRounds>=4&&x.avgRounds<=12).length;s+=mis.filter(x=>x.winRate>.65).length*2;const runaway=r.filter(x=>x.damage.p99>500).length;s-=runaway*3;score[m]={score:s,runaway};}return score;}
const runs=Number(process.argv.find(x=>x.startsWith('--runs='))?.split('=')[1]||600),out=process.argv.find(x=>x.startsWith('--output='))?.split('=')[1]||'p1-results';const rows=run(runs),v=verdict(rows);fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'p1-results.json'),JSON.stringify({runsPerCell:runs,totalFights:rows.length*runs,verdict:v,rows},null,2));const ranked=Object.entries(v).sort((a,b)=>b[1].score-a[1].score);let md=`# P1 Pattern / Impact Gate\n\nFights: **${rows.length*runs.toLocaleString()}** across ${rows.length} build/policy/enemy/model cells. Shipping combat unchanged.\n\n## Model screen\n\n| Model | Gate score | Runaway cells |\n|---|---:|---:|\n`;for(const [m,x] of ranked)md+=`| ${m} | ${x.score} | ${x.runaway} |\n`;md+=`\nProvisional leader: **${ranked[0][0]}**. This score is a screening heuristic; inspect telemetry before promotion.\n\n## Opportunist summaries\n`;for(const m of['A','B','C','D']){md+=`\n### Model ${m}\n| Build | Enemy | Win | Rounds | Median dmg | P99 | Manip/fight | Tension |\n|---|---|---:|---:|---:|---:|---:|---:|\n`;for(const x of rows.filter(z=>z.model===m&&z.policy==='opportunist'))md+=`| ${x.build} | ${x.kind} | ${(x.winRate*100).toFixed(1)}% | ${x.avgRounds.toFixed(2)} | ${x.damage.median} | ${x.damage.p99} | ${x.manipPerFight.toFixed(2)} | ${(x.tensionRate*100).toFixed(1)}% |\n`;}fs.writeFileSync(path.join(out,'P1_REPORT.md'),md);console.log(md);