import fs from "node:fs";
import path from "node:path";
import { batch } from "./simulator.mjs";

const args=Object.fromEntries(process.argv.slice(2).map((arg)=>{
  const [key,value="true"]=arg.replace(/^--/,"").split("="); return [key,value];
}));
const runs=Math.max(1,Number.parseInt(args.runs??"1000",10));
const seedBase=Number.parseInt(args.seedBase??"100000",10);
const result={version:"shared-core-e5-v1",runsPerPolicy:runs,seedBase,coverage:{events:"not-yet-modeled",activeItems:"Field Adjustment + Mirror Shard + Hidden Hand + Carbon Paper + Blank Face",passiveEffects:"core-driven subset"},policies:batch({runs,seedBase})};

console.log(JSON.stringify(result,null,2));
if(args.output){
  const dir=path.resolve(args.output); fs.mkdirSync(dir,{recursive:true});
  fs.writeFileSync(path.join(dir,"summary.json"),JSON.stringify(result,null,2));
  const lines=["# Shared-Core Simulation E5 V1","",`Runs per policy: **${runs}**`,"","| Policy | Clear | Avg HP | Damage | Rounds | Spoils | B1 | B2 | B3 | B4 |","|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"];
  for(const [policy,s] of Object.entries(result.policies)){
    const b=s.bandFrequency; const pct=(x)=>(x*100).toFixed(1)+"%";
    lines.push(`| ${policy} | ${pct(s.clearRate)} | ${s.avgFinalHp.toFixed(2)} | ${s.avgDamageTaken.toFixed(2)} | ${s.avgRounds.toFixed(2)} | ${s.avgSpoils.toFixed(2)} | ${pct(b[1])} | ${pct(b[2])} | ${pct(b[3])} | ${pct(b[4])} |`);
  }
  lines.push("","## Coverage note","","This report is generated by a simulator that imports `engine/core/dist`. Events and several post-resolution/consumable effects are explicitly not modeled yet; do not treat this as the final Floor I balance freeze.");
  fs.writeFileSync(path.join(dir,"REPORT.md"),lines.join("\n"));
}
