import fs from "node:fs";
import path from "node:path";
import { batch } from "./simulator.mjs";

const args=Object.fromEntries(process.argv.slice(2).map((arg)=>{const [key,value="true"]=arg.replace(/^--/,"").split("=");return[key,value];}));
const runs=Math.max(1,Number.parseInt(args.runs??"1000",10));
const seedBase=Number.parseInt(args.seedBase??"100000",10);
const result={
  version:"shared-core-e6-v2",runsPerPolicy:runs,seedBase,
  coverage:{
    events:"Floor I choices/outcomes modeled through core EventResolver",
    enemyRules:"tie rules, fixed-die rules, and manipulation reactions now core-owned",
    activeItems:"Field Adjustment + Mirror Shard + Hidden Hand + Carbon Paper + Blank Face",
    passiveEffects:"Gear/Artifact subset plus Long Odds through core EffectResolver",
    remaining:"Contraband policy, Brass Caliper, Stuck Key, Ash Ledger, Receipt From Nowhere, Small Change Purse"
  },
  policies:batch({runs,seedBase})
};
console.log(JSON.stringify(result,null,2));

const pct=(x)=>(x*100).toFixed(1)+"%";
if(args.output){
  const dir=path.resolve(args.output);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,"summary.json"),JSON.stringify(result,null,2));
  const lines=[
    "# Shared-Core Simulation E6 V2","",`Runs per policy: **${runs}**`,"",
    "| Policy | Clear | Avg HP | Damage | Rounds | Spoils | Raw B4 | Reward B4 | Elite visits |",
    "|---|---:|---:|---:|---:|---:|---:|---:|---:|"
  ];
  for(const[policy,s]of Object.entries(result.policies))lines.push(`| ${policy} | ${pct(s.clearRate)} | ${s.avgFinalHp.toFixed(2)} | ${s.avgDamageTaken.toFixed(2)} | ${s.avgRounds.toFixed(2)} | ${s.avgSpoils.toFixed(2)} | ${pct(s.rawBandFrequency[4])} | ${pct(s.rewardBandFrequency[4])} | ${s.avgElites.toFixed(2)} |`);
  lines.push("","## Raw Final-Blow Spoils bands","","| Policy | B1 | B2 | B3 | B4 |","|---|---:|---:|---:|---:|");
  for(const[policy,s]of Object.entries(result.policies))lines.push(`| ${policy} | ${pct(s.rawBandFrequency[1])} | ${pct(s.rawBandFrequency[2])} | ${pct(s.rawBandFrequency[3])} | ${pct(s.rawBandFrequency[4])} |`);
  lines.push("","## Post-Elite reward bands","","| Policy | B1 | B2 | B3 | B4 |","|---|---:|---:|---:|---:|");
  for(const[policy,s]of Object.entries(result.policies))lines.push(`| ${policy} | ${pct(s.rewardBandFrequency[1])} | ${pct(s.rewardBandFrequency[2])} | ${pct(s.rewardBandFrequency[3])} | ${pct(s.rewardBandFrequency[4])} |`);
  lines.push("","## Boss pressure","","| Policy | Boss clear | Entry HP | Boss rounds | Boss damage |","|---|---:|---:|---:|---:|");
  for(const[policy,s]of Object.entries(result.policies))lines.push(`| ${policy} | ${pct(s.boss.clearRate)} | ${s.boss.avgEntryHp.toFixed(2)} | ${s.boss.avgRounds.toFixed(2)} | ${s.boss.avgPlayerDamage.toFixed(2)} |`);
  lines.push("","## Per-enemy pressure — Opportunist","","| Enemy | Attempts | Win | Rounds | Damage | Spoils |","|---|---:|---:|---:|---:|---:|");
  for(const[id,e]of Object.entries(result.policies.opportunist.encounters).sort((a,b)=>a[0].localeCompare(b[0])))lines.push(`| ${id} | ${e.attempts} | ${pct(e.winRate)} | ${e.avgRounds.toFixed(2)} | ${e.avgPlayerDamage.toFixed(2)} | ${e.avgSpoils.toFixed(2)} |`);
  lines.push("","## Coverage note","","This report is generated by a simulator importing `engine/core/dist`. Raw Spoils band is separated from Elite reward-band uplift. Tie rules, Long Odds, and manipulation-reactive enemies resolve through production-core systems. Remaining E6 player-content coverage is explicit above; do not declare final balance until those material effects are represented or intentionally excluded.");
  fs.writeFileSync(path.join(dir,"REPORT.md"),lines.join("\n"));
}
