import type { EffectDefinition } from "../effects/effects.js";

export const bentKnifeEffect: EffectDefinition = {id:"gear:bent-knife:different-plus1",sourceId:"gear:bent-knife",timing:"FIGHT_MODIFICATION",priority:300,condition:{type:"fight_dice_different"},actions:[{type:"add_fight",value:1}]};
export const twinNailsEffect: EffectDefinition = {id:"gear:twin-nails:doubles-plus2",sourceId:"gear:twin-nails",timing:"FIGHT_MODIFICATION",priority:300,condition:{type:"fight_dice_doubles"},actions:[{type:"add_fight",value:2}]};\nexport const twinNailsImpactEffect: EffectDefinition = {id:"gear:twin-nails:doubles-impact",sourceId:"gear:twin-nails",timing:"DAMAGE_MODIFICATION",priority:520,condition:{type:"fight_dice_doubles"},actions:[{type:"multiply_damage_to_enemy",factor:2,cap:24}]};
export const breachingBarEffect: EffectDefinition = {id:"gear:breaching-bar:raw10-bonus",sourceId:"gear:breaching-bar",timing:"DAMAGE_MODIFICATION",priority:300,condition:{type:"raw_fight_at_least",value:10},actions:[{type:"add_damage_to_enemy",value:2}]};
export const workApronEffect: EffectDefinition = {id:"gear:work-apron:first-reduction",sourceId:"gear:work-apron",timing:"DAMAGE_MODIFICATION",priority:300,condition:{type:"player_damage_at_least",value:1},actions:[{type:"reduce_player_damage",value:1}],maxUsesPerEncounter:1};
export const proofVestEffect: EffectDefinition = {id:"gear:proof-vest:first-reduction",sourceId:"gear:proof-vest",timing:"DAMAGE_MODIFICATION",priority:300,condition:{type:"player_damage_at_least",value:1},actions:[{type:"reduce_player_damage",value:2}],maxUsesPerEncounter:1};
export const insideOutLiningEffect: EffectDefinition = {id:"gear:inside-out-lining:loss1-zero",sourceId:"gear:inside-out-lining",timing:"DAMAGE_MODIFICATION",priority:300,condition:{type:"margin_exact",value:-1},actions:[{type:"reduce_player_damage",value:1}],maxUsesPerEncounter:1};
export const brassBuckleEffect: EffectDefinition = {id:"gear:brass-buckle:tie-chip",sourceId:"gear:brass-buckle",timing:"TIE_RESOLUTION",priority:300,condition:{type:"outcome",value:"tie"},actions:[{type:"add_damage_to_enemy",value:1}]};

export const loadedQuestionEffect: EffectDefinition = {id:"artifact:loaded-question:doubles",sourceId:"artifact:loaded-question",timing:"SPOILS_MODIFICATION",priority:400,condition:{type:"spoils_doubles"},actions:[{type:"add_spoils_score",value:2,cap:12}]};\nexport const loadedQuestionFourKindImpactEffect: EffectDefinition = {id:"artifact:loaded-question:four-kind-impact",sourceId:"artifact:loaded-question",timing:"DAMAGE_MODIFICATION",priority:620,condition:{type:"cast_four_kind"},actions:[{type:"multiply_damage_to_enemy",factor:2,cap:48}]};
export const falseBottomEffect: EffectDefinition = {id:"artifact:false-bottom:low-spoils",sourceId:"artifact:false-bottom",timing:"SPOILS_MODIFICATION",priority:410,condition:{type:"spoils_score_at_most",value:5},actions:[{type:"add_spoils_score",value:2,cap:12}]};
export const oppositeNumberEffect: EffectDefinition = {id:"artifact:opposite-number:opposites",sourceId:"artifact:opposite-number",timing:"SPOILS_MODIFICATION",priority:420,condition:{type:"spoils_opposites"},actions:[{type:"add_spoils_score",value:3,cap:12}]};
export const redThreadEffect: EffectDefinition = {id:"artifact:red-thread:margin1-heal",sourceId:"artifact:red-thread",timing:"DAMAGE_MODIFICATION",priority:400,condition:{type:"margin_exact",value:1},actions:[{type:"heal_player",value:1}],maxUsesPerEncounter:1};
export const longOddsEffect: EffectDefinition = {id:"technique:long-odds:margin1-spoils",sourceId:"technique:long-odds",timing:"SPOILS_MODIFICATION",priority:350,condition:{type:"margin_exact",value:1},actions:[{type:"add_spoils_score",value:2,cap:12}],maxUsesPerEncounter:1};

export const tollEaterGreedTaxEffect: EffectDefinition = {id:"enemy:toll-eater:take-your-cut",sourceId:"enemy:toll-eater",timing:"FIGHT_MODIFICATION",priority:100,condition:{type:"spoils_score_at_least",value:9},actions:[{type:"add_fight",value:-1}]};
export const passageClerkDuplicateFilingEffect: EffectDefinition = {id:"enemy:passage-clerk:duplicate-filing",sourceId:"enemy:passage-clerk",timing:"FIGHT_MODIFICATION",priority:100,condition:{type:"fight_dice_doubles"},actions:[{type:"add_enemy_fight",value:2}]};
export const sealWhelpReactionEffect: EffectDefinition = {id:"enemy:seal-whelp:reaction-seal",sourceId:"enemy:seal-whelp",timing:"FIGHT_MODIFICATION",priority:100,condition:{type:"always"},actions:[{type:"add_enemy_fight",value:1}],maxUsesPerEncounter:1};
export const turnbackRefusalEffect: EffectDefinition = {id:"rule:turnback:refusal",sourceId:"enemy:turnback",timing:"TIE_RESOLUTION",priority:100,condition:{type:"outcome",value:"tie"},actions:[{type:"heal_enemy",value:1}]};
export const firstDoorAjarDraftEffect: EffectDefinition = {id:"boss:first-door:ajar-draft",sourceId:"boss:first-door",timing:"FIGHT_MODIFICATION",priority:100,condition:{type:"spoils_greater_than_raw_fight"},actions:[{type:"add_enemy_fight",value:1}]};
export const firstDoorBothWaysEffect: EffectDefinition = {id:"rule:first-door:both-ways",sourceId:"boss:first-door",timing:"TIE_RESOLUTION",priority:100,condition:{type:"outcome",value:"tie"},actions:[{type:"add_damage_to_enemy",value:2},{type:"add_damage_to_player",value:2}]};

export const floor1EffectRegistry: Readonly<Record<string,EffectDefinition>> = Object.fromEntries([
  bentKnifeEffect,twinNailsEffect,breachingBarEffect,workApronEffect,proofVestEffect,insideOutLiningEffect,brassBuckleEffect,
  loadedQuestionEffect,falseBottomEffect,oppositeNumberEffect,redThreadEffect,longOddsEffect,
  tollEaterGreedTaxEffect,passageClerkDuplicateFilingEffect,sealWhelpReactionEffect,turnbackRefusalEffect,firstDoorAjarDraftEffect,firstDoorBothWaysEffect,
].map((effect)=>[effect.id,effect]));
